# Generated by Django 5.2.1 on 2025-05-13 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Formacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("centro", models.CharField(max_length=200)),
                ("descripcion", models.TextField(blank=True)),
                ("anio", models.PositiveIntegerField()),
                (
                    "icono",
                    models.CharField(
                        help_text="Clase de FontAwesome, ej: 'fa-solid fa-code'",
                        max_length=100,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tecnologia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                (
                    "icono",
                    models.CharField(
                        help_text="Clase de FontAwesome, ej: 'fa-brands fa-python'",
                        max_length=100,
                    ),
                ),
            ],
        ),
    ]
