# Generated by Django 5.2.1 on 2025-05-13 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_proyecto_conclusion_tecnologiasproyecto"),
    ]

    operations = [
        migrations.AddField(
            model_name="parrafoproyecto",
            name="titulo",
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
